# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'backend_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61\x63kend_service.proto\x12\x0f\x62\x61\x63kend_service\"w\n\x10StartTaskRequest\x12\x13\n\x0btask_prompt\x18\x01 \x01(\t\x12\x11\n\tmax_steps\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x14\n\x0c\x62rowser_name\x18\x04 \x01(\t\x12\x14\n\x0c\x62rowser_port\x18\x05 \x01(\x05\"F\n\x11StartTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\'\n\x14GetTaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"I\n\x15GetTaskStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\x11\x43\x61ncelTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"6\n\x12\x43\x61ncelTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9b\x02\n\x0e\x42\x61\x63kendService\x12R\n\tStartTask\x12!.backend_service.StartTaskRequest\x1a\".backend_service.StartTaskResponse\x12^\n\rGetTaskStatus\x12%.backend_service.GetTaskStatusRequest\x1a&.backend_service.GetTaskStatusResponse\x12U\n\nCancelTask\x12\".backend_service.CancelTaskRequest\x1a#.backend_service.CancelTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTTASKREQUEST']._serialized_start=42
  _globals['_STARTTASKREQUEST']._serialized_end=161
  _globals['_STARTTASKRESPONSE']._serialized_start=163
  _globals['_STARTTASKRESPONSE']._serialized_end=233
  _globals['_GETTASKSTATUSREQUEST']._serialized_start=235
  _globals['_GETTASKSTATUSREQUEST']._serialized_end=274
  _globals['_GETTASKSTATUSRESPONSE']._serialized_start=276
  _globals['_GETTASKSTATUSRESPONSE']._serialized_end=349
  _globals['_CANCELTASKREQUEST']._serialized_start=351
  _globals['_CANCELTASKREQUEST']._serialized_end=387
  _globals['_CANCELTASKRESPONSE']._serialized_start=389
  _globals['_CANCELTASKRESPONSE']._serialized_end=443
  _globals['_BACKENDSERVICE']._serialized_start=446
  _globals['_BACKENDSERVICE']._serialized_end=729
# @@protoc_insertion_point(module_scope)
