# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: browser_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'browser_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62rowser_service.proto\x12\x0f\x62rowser_service\"9\n\x13StartBrowserRequest\x12\x14\n\x0c\x62rowser_name\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"^\n\x14StartBrowserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x64p_url\x18\x03 \x01(\t\x12\x13\n\x0bws_endpoint\x18\x04 \x01(\t\"\"\n\x12StopBrowserRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\"7\n\x13StopBrowserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"+\n\x1bGetBrowserConnectionRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\"o\n\x1cGetBrowserConnectionResponse\x12\x0f\n\x07running\x18\x01 \x01(\x08\x12\x0f\n\x07\x63\x64p_url\x18\x02 \x01(\t\x12\x13\n\x0bws_endpoint\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\"\'\n\x17IsBrowserRunningRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\"+\n\x18IsBrowserRunningResponse\x12\x0f\n\x07running\x18\x01 \x01(\x08\x32\xa5\x03\n\x0e\x42rowserService\x12[\n\x0cStartBrowser\x12$.browser_service.StartBrowserRequest\x1a%.browser_service.StartBrowserResponse\x12X\n\x0bStopBrowser\x12#.browser_service.StopBrowserRequest\x1a$.browser_service.StopBrowserResponse\x12s\n\x14GetBrowserConnection\x12,.browser_service.GetBrowserConnectionRequest\x1a-.browser_service.GetBrowserConnectionResponse\x12g\n\x10IsBrowserRunning\x12(.browser_service.IsBrowserRunningRequest\x1a).browser_service.IsBrowserRunningResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'browser_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTBROWSERREQUEST']._serialized_start=42
  _globals['_STARTBROWSERREQUEST']._serialized_end=99
  _globals['_STARTBROWSERRESPONSE']._serialized_start=101
  _globals['_STARTBROWSERRESPONSE']._serialized_end=195
  _globals['_STOPBROWSERREQUEST']._serialized_start=197
  _globals['_STOPBROWSERREQUEST']._serialized_end=231
  _globals['_STOPBROWSERRESPONSE']._serialized_start=233
  _globals['_STOPBROWSERRESPONSE']._serialized_end=288
  _globals['_GETBROWSERCONNECTIONREQUEST']._serialized_start=290
  _globals['_GETBROWSERCONNECTIONREQUEST']._serialized_end=333
  _globals['_GETBROWSERCONNECTIONRESPONSE']._serialized_start=335
  _globals['_GETBROWSERCONNECTIONRESPONSE']._serialized_end=446
  _globals['_ISBROWSERRUNNINGREQUEST']._serialized_start=448
  _globals['_ISBROWSERRUNNINGREQUEST']._serialized_end=487
  _globals['_ISBROWSERRUNNINGRESPONSE']._serialized_start=489
  _globals['_ISBROWSERRUNNINGRESPONSE']._serialized_end=532
  _globals['_BROWSERSERVICE']._serialized_start=535
  _globals['_BROWSERSERVICE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
