# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import browser_service_pb2 as browser__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in browser_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrowserServiceStub(object):
    """Browser Service - Manages Playwright browser instances
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBrowser = channel.unary_unary(
                '/browser_service.BrowserService/StartBrowser',
                request_serializer=browser__service__pb2.StartBrowserRequest.SerializeToString,
                response_deserializer=browser__service__pb2.StartBrowserResponse.FromString,
                _registered_method=True)
        self.StopBrowser = channel.unary_unary(
                '/browser_service.BrowserService/StopBrowser',
                request_serializer=browser__service__pb2.StopBrowserRequest.SerializeToString,
                response_deserializer=browser__service__pb2.StopBrowserResponse.FromString,
                _registered_method=True)
        self.GetBrowserConnection = channel.unary_unary(
                '/browser_service.BrowserService/GetBrowserConnection',
                request_serializer=browser__service__pb2.GetBrowserConnectionRequest.SerializeToString,
                response_deserializer=browser__service__pb2.GetBrowserConnectionResponse.FromString,
                _registered_method=True)
        self.IsBrowserRunning = channel.unary_unary(
                '/browser_service.BrowserService/IsBrowserRunning',
                request_serializer=browser__service__pb2.IsBrowserRunningRequest.SerializeToString,
                response_deserializer=browser__service__pb2.IsBrowserRunningResponse.FromString,
                _registered_method=True)


class BrowserServiceServicer(object):
    """Browser Service - Manages Playwright browser instances
    """

    def StartBrowser(self, request, context):
        """Start a browser instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopBrowser(self, request, context):
        """Stop a browser instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBrowserConnection(self, request, context):
        """Get browser connection info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsBrowserRunning(self, request, context):
        """Check if browser is running
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrowserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBrowser,
                    request_deserializer=browser__service__pb2.StartBrowserRequest.FromString,
                    response_serializer=browser__service__pb2.StartBrowserResponse.SerializeToString,
            ),
            'StopBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.StopBrowser,
                    request_deserializer=browser__service__pb2.StopBrowserRequest.FromString,
                    response_serializer=browser__service__pb2.StopBrowserResponse.SerializeToString,
            ),
            'GetBrowserConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrowserConnection,
                    request_deserializer=browser__service__pb2.GetBrowserConnectionRequest.FromString,
                    response_serializer=browser__service__pb2.GetBrowserConnectionResponse.SerializeToString,
            ),
            'IsBrowserRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.IsBrowserRunning,
                    request_deserializer=browser__service__pb2.IsBrowserRunningRequest.FromString,
                    response_serializer=browser__service__pb2.IsBrowserRunningResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'browser_service.BrowserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('browser_service.BrowserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrowserService(object):
    """Browser Service - Manages Playwright browser instances
    """

    @staticmethod
    def StartBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser_service.BrowserService/StartBrowser',
            browser__service__pb2.StartBrowserRequest.SerializeToString,
            browser__service__pb2.StartBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser_service.BrowserService/StopBrowser',
            browser__service__pb2.StopBrowserRequest.SerializeToString,
            browser__service__pb2.StopBrowserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBrowserConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser_service.BrowserService/GetBrowserConnection',
            browser__service__pb2.GetBrowserConnectionRequest.SerializeToString,
            browser__service__pb2.GetBrowserConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsBrowserRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser_service.BrowserService/IsBrowserRunning',
            browser__service__pb2.IsBrowserRunningRequest.SerializeToString,
            browser__service__pb2.IsBrowserRunningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
