# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import database_service_pb2 as database__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in database_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatabaseServiceStub(object):
    """Database Service - Manages MongoDB operations for tasks
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/database_service.DatabaseService/CreateTask',
                request_serializer=database__service__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=database__service__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/database_service.DatabaseService/GetTask',
                request_serializer=database__service__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=database__service__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/database_service.DatabaseService/ListTasks',
                request_serializer=database__service__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=database__service__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.SaveTaskOutput = channel.unary_unary(
                '/database_service.DatabaseService/SaveTaskOutput',
                request_serializer=database__service__pb2.SaveTaskOutputRequest.SerializeToString,
                response_deserializer=database__service__pb2.SaveTaskOutputResponse.FromString,
                _registered_method=True)
        self.GetTaskHistory = channel.unary_unary(
                '/database_service.DatabaseService/GetTaskHistory',
                request_serializer=database__service__pb2.GetTaskHistoryRequest.SerializeToString,
                response_deserializer=database__service__pb2.GetTaskHistoryResponse.FromString,
                _registered_method=True)
        self.UpdateTaskStatus = channel.unary_unary(
                '/database_service.DatabaseService/UpdateTaskStatus',
                request_serializer=database__service__pb2.UpdateTaskStatusRequest.SerializeToString,
                response_deserializer=database__service__pb2.UpdateTaskStatusResponse.FromString,
                _registered_method=True)


class DatabaseServiceServicer(object):
    """Database Service - Manages MongoDB operations for tasks
    """

    def CreateTask(self, request, context):
        """Create a new task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Get a task by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """List all tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveTaskOutput(self, request, context):
        """Save task output/step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskHistory(self, request, context):
        """Get task history/outputs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskStatus(self, request, context):
        """Update task status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=database__service__pb2.CreateTaskRequest.FromString,
                    response_serializer=database__service__pb2.CreateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=database__service__pb2.GetTaskRequest.FromString,
                    response_serializer=database__service__pb2.GetTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=database__service__pb2.ListTasksRequest.FromString,
                    response_serializer=database__service__pb2.ListTasksResponse.SerializeToString,
            ),
            'SaveTaskOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveTaskOutput,
                    request_deserializer=database__service__pb2.SaveTaskOutputRequest.FromString,
                    response_serializer=database__service__pb2.SaveTaskOutputResponse.SerializeToString,
            ),
            'GetTaskHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskHistory,
                    request_deserializer=database__service__pb2.GetTaskHistoryRequest.FromString,
                    response_serializer=database__service__pb2.GetTaskHistoryResponse.SerializeToString,
            ),
            'UpdateTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskStatus,
                    request_deserializer=database__service__pb2.UpdateTaskStatusRequest.FromString,
                    response_serializer=database__service__pb2.UpdateTaskStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'database_service.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('database_service.DatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Database Service - Manages MongoDB operations for tasks
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/database_service.DatabaseService/CreateTask',
            database__service__pb2.CreateTaskRequest.SerializeToString,
            database__service__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/database_service.DatabaseService/GetTask',
            database__service__pb2.GetTaskRequest.SerializeToString,
            database__service__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/database_service.DatabaseService/ListTasks',
            database__service__pb2.ListTasksRequest.SerializeToString,
            database__service__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveTaskOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/database_service.DatabaseService/SaveTaskOutput',
            database__service__pb2.SaveTaskOutputRequest.SerializeToString,
            database__service__pb2.SaveTaskOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/database_service.DatabaseService/GetTaskHistory',
            database__service__pb2.GetTaskHistoryRequest.SerializeToString,
            database__service__pb2.GetTaskHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/database_service.DatabaseService/UpdateTaskStatus',
            database__service__pb2.UpdateTaskStatusRequest.SerializeToString,
            database__service__pb2.UpdateTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
